# Generated by Django 2.2.5 on 2021-01-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
