# Generated by Django 2.2.5 on 2021-04-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_app_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(),
        ),
    ]
