# Generated by Django 2.2.5 on 2021-05-07 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='avatar',
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='avatar_default.jpg', null=True, upload_to='fotos_de_perfiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 13, 51, 9, 699708)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 13, 51, 9, 699734)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 13, 51, 9, 715196, tzinfo=utc)),
        ),
    ]
