# Generated by Django 2.2.5 on 2021-01-04 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0002_auto_20210104_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 1, 25, 47, 315379)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 1, 25, 47, 315406)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 1, 25, 47, 330426, tzinfo=utc)),
        ),
    ]
