# Generated by Django 2.2.5 on 2021-05-07 14:12

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0002_auto_20210507_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 14, 12, 23, 432772)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 14, 12, 23, 432797)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 14, 12, 23, 448182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='card',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='in_insmet_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='scholar_lvl',
            field=models.CharField(blank=True, choices=[('M', 'Medio'), ('S', 'Superior')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('B', 'Blanca'), ('M', 'Mestiza'), ('N', 'Negra')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_category',
            field=models.CharField(blank=True, choices=[('T', 'Técnico'), ('E', 'Especialista')], max_length=20, null=True),
        ),
    ]
