# Generated by Django 2.2.5 on 2021-01-06 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0004_auto_20210104_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='indexade',
            new_name='indexed',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='arbitrade',
            new_name='refereed',
        ),
        migrations.RemoveField(
            model_name='article',
            name='magazibe',
        ),
        migrations.AddField(
            model_name='article',
            name='magazine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='impact_level',
            field=models.CharField(blank=True, choices=[('I', 'Grupo I'), ('II', 'Grupo II'), ('III', 'Grupo III'), ('IV', 'Grupo IV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 19, 4, 15, 901611)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 19, 4, 15, 901637)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 19, 4, 15, 916856, tzinfo=utc)),
        ),
    ]
