# Generated by Django 2.2.5 on 2021-05-07 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0004_auto_20210507_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='user_avatar/default.jpg', null=True, upload_to='user_avatar/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 16, 32, 0, 355193)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 16, 32, 0, 355219)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 16, 32, 0, 370447, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('B', 'Baja'), ('EU', 'En uso'), ('PB', 'Proceso de baja'), ('R', 'Roto')], max_length=20)),
                ('x_file', models.BooleanField(default=False)),
                ('accounting_inventory', models.BooleanField(default=True)),
                ('computer_item', models.BooleanField(default=False)),
                ('loan_request', models.FileField(blank=True, null=True, upload_to='')),
                ('loan_letter', models.FileField(blank=True, null=True, upload_to='')),
                ('loan', models.BooleanField(default=False)),
                ('transfer', models.BooleanField(default=False)),
                ('transfer_letter_place', models.FileField(blank=True, null=True, upload_to='')),
                ('transfer_letter_economy', models.FileField(blank=True, null=True, upload_to='')),
                ('observations', models.TextField(blank=True, null=True)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piloto.Object')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piloto.Office')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='piloto.Project')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='piloto.Worker')),
            ],
        ),
    ]
