# Generated by Django 2.2.5 on 2021-01-10 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0005_auto_20210106_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager_por_cfa',
            new_name='manager_by_cfa',
        ),
        migrations.RemoveField(
            model_name='project',
            name='presupuesto_anno',
        ),
        migrations.RemoveField(
            model_name='project',
            name='presupuesto_total',
        ),
        migrations.AlterField(
            model_name='person',
            name='scientific_grade',
            field=models.CharField(blank=True, choices=[('MSc', 'Master'), ('Dr', 'Doctor(a)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 23, 27, 30, 282408)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 23, 27, 30, 282433)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 23, 27, 30, 297502, tzinfo=utc)),
        ),
    ]
