# Generated by Django 2.2.5 on 2021-01-11 23:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0006_auto_20210110_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='refereed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 11, 23, 36, 29, 400069)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 11, 23, 36, 29, 400095)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 11, 23, 36, 29, 415438, tzinfo=utc)),
        ),
    ]
