# Generated by Django 2.2.5 on 2021-01-12 02:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0009_auto_20210112_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 2, 3, 9, 313057)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 2, 3, 9, 313083)),
        ),
        migrations.AlterField(
            model_name='scienceprize',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 2, 3, 9, 328624, tzinfo=utc)),
        ),
    ]
