# Generated by Django 2.2.5 on 2021-01-12 02:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0010_auto_20210112_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencyrealized',
            name='ponency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='editions', to='piloto.Ponency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 2, 20, 18, 820618)),
        ),
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.CharField(blank=True, choices=[('PP', 'Programa Priorizado'), ('PE', 'Proyecto Empresarial'), ('INF', 'Institucional ft'), ('IN', 'Institucional')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 2, 20, 18, 820645)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 2, 20, 18, 836160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('EST', 'Estatal'), ('COM', 'Comercial'), ('EXP', 'Exportación')], max_length=20, null=True),
        ),
    ]
