# Generated by Django 2.2.5 on 2021-01-12 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0011_auto_20210112_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseedition',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='courseedition',
            old_name='start',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='aproved_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 20, 23, 58, 63667)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 20, 23, 58, 63694)),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 20, 23, 58, 81063, tzinfo=utc)),
        ),
    ]
